import type { BrandLogoSource } from '../types'

const logoPath = (fileName: string) => `/camera-logos/${encodeURIComponent(fileName)}`

export const cameraLogoCatalog: BrandLogoSource[] = [
  {
    id: 'apple',
    name: 'Apple',
    aliases: ['apple', 'iphone', 'ipad'],
    assets: { black: logoPath('Apple_Black.svg'), white: logoPath('Apple_White.svg') },
  },
  {
    id: 'canon',
    name: 'Canon',
    aliases: ['canon', 'eos', 'powershot'],
    brandColor: '#c31322',
    assets: {
      color: logoPath('Canon_Color.svg'),
      black: logoPath('Canon_Black.svg'),
      white: logoPath('Canon_White.svg'),
    },
  },
  {
    id: 'sony',
    name: 'Sony',
    aliases: ['sony', 'alpha', 'a7', 'a9', 'zv-e', 'rx100'],
    assets: { black: logoPath('SONY_Black.svg'), white: logoPath('SONY_White.svg') },
  },
  {
    id: 'sony-alpha',
    name: 'Sony Alpha',
    aliases: ['sony alpha', 'alpha'],
    assets: { black: logoPath('SONYalpha_Black.svg'), white: logoPath('SONYalpha_White.svg') },
  },
  {
    id: 'nikon',
    name: 'Nikon',
    aliases: ['nikon', 'z fc', 'z 5', 'z 6', 'z 7', 'z 8', 'z 9'],
    brandColor: '#ffd400',
    assets: {
      color: logoPath('Nikon_Color.svg'),
      black: logoPath('Nikon_Black.svg'),
      white: logoPath('Nikon_White.svg'),
    },
  },
  {
    id: 'fujifilm',
    name: 'Fujifilm',
    aliases: ['fujifilm', 'fuji', 'x-t', 'x100', 'gfx'],
    brandColor: '#e60012',
    assets: {
      color: logoPath('Fujifilm_Color.svg'),
      black: logoPath('Fujifilm_BLack.svg'),
      white: logoPath('Fujifilm_White.svg'),
    },
  },
  {
    id: 'leica',
    name: 'Leica',
    aliases: ['leica', 'summilux', 'summicron'],
    brandColor: '#e20612',
    assets: {
      color: logoPath('Leica_Color.svg'),
      black: logoPath('Leica_Black.svg'),
      white: logoPath('Leica_White.svg'),
    },
  },
  {
    id: 'panasonic',
    name: 'Panasonic',
    aliases: ['panasonic', 'lumix', 'gh6', 's5m2'],
    brandColor: '#0041c0',
    assets: { color: logoPath('panasonic_Color.svg') },
  },
  {
    id: 'lumix',
    name: 'Lumix',
    aliases: ['lumix'],
    assets: { black: logoPath('Lumix_Black.svg'), white: logoPath('Lumix_White.svg') },
  },
  {
    id: 'dji',
    name: 'DJI',
    aliases: ['dji', 'mavic', 'pocket'],
    assets: { black: logoPath('DJI_Black.svg'), white: logoPath('DJI_White.svg') },
  },
  {
    id: 'osmo-action',
    name: 'Osmo Action',
    aliases: ['osmo action', 'osmo'],
    assets: { black: logoPath('Osmo_Action_Black.svg'), white: logoPath('Osmo_Action_White.svg') },
  },
  {
    id: 'insta360',
    name: 'Insta360',
    aliases: ['insta360'],
    assets: { black: logoPath('Insta360_Black.svg'), white: logoPath('Insta360_White.svg') },
  },
  {
    id: 'gopro',
    name: 'GoPro',
    aliases: ['gopro', 'hero'],
    assets: {
      color: logoPath('GoPro_Color.svg'),
      black: logoPath('GoPro_Black.svg'),
      white: logoPath('GoPro_White.svg'),
    },
  },
  {
    id: 'hasselblad',
    name: 'Hasselblad',
    aliases: ['hasselblad'],
    assets: { black: logoPath('hasselblad-Black.svg'), white: logoPath('hasselblad-White.svg') },
  },
  {
    id: 'ricoh',
    name: 'Ricoh',
    aliases: ['ricoh', 'gr iii', 'gr3'],
    brandColor: '#d71920',
    assets: { color: logoPath('Ricoh_Color.svg') },
  },
  {
    id: 'sigma',
    name: 'Sigma',
    aliases: ['sigma'],
    assets: {
      black: logoPath('SIGMA_Black.svg'),
      white: logoPath('SIGMA_White.svg'),
    },
  },
  {
    id: 'tamron',
    name: 'Tamron',
    aliases: ['tamron'],
    brandColor: '#004ea2',
    assets: {
      color: logoPath('TAMRON_Color.svg'),
      black: logoPath('TAMRON_Black.svg'),
      white: logoPath('TAMRON_White.svg'),
    },
  },
  {
    id: 'tokina',
    name: 'Tokina',
    aliases: ['tokina'],
    brandColor: '#005baa',
    assets: {
      color: logoPath('Tokina_Color.svg'),
      black: logoPath('Tokina_Black.svg'),
      white: logoPath('Tokina_White.svg'),
    },
  },
  {
    id: 'zeiss',
    name: 'ZEISS',
    aliases: ['zeiss', 'carl zeiss'],
    brandColor: '#0050a4',
    assets: {
      color: logoPath('ZEISS_Color.svg'),
      black: logoPath('ZEISS_Black.svg'),
      white: logoPath('ZEISS_White.svg'),
    },
  },
  {
    id: 'minolta',
    name: 'Minolta',
    aliases: ['minolta'],
    brandColor: '#005baa',
    assets: { color: logoPath('Minolta_Color.svg') },
  },
  {
    id: 'phaseone',
    name: 'Phase One',
    aliases: ['phase one', 'phaseone'],
    assets: { color: logoPath('phaseone_Color.svg'), white: logoPath('phaseone_White.svg') },
  },
  {
    id: 'samsung',
    name: 'Samsung',
    aliases: ['samsung', 'galaxy'],
    assets: {
      black: logoPath('Samsung_black-1.svg'),
      white: logoPath('Samsung_White.svg'),
    },
  },
  {
    id: 'huawei',
    name: 'Huawei',
    aliases: ['huawei', 'mate', 'pura'],
    brandColor: '#d20a2e',
    assets: {
      color: logoPath('Huawei_Color.svg'),
      black: logoPath('Huawei_Black.svg'),
      white: logoPath('Huawei_White.svg'),
    },
  },
  {
    id: 'xiaomi',
    name: 'Xiaomi',
    aliases: ['xiaomi', 'mi '],
    brandColor: '#ff6900',
    assets: { color: logoPath('Xiaomi.svg'), black: logoPath('Xiaomi_Black.svg'), white: logoPath('Xiaomi_White.svg') },
  },
  {
    id: 'redmi',
    name: 'Redmi',
    aliases: ['redmi'],
    brandColor: '#ff6900',
    assets: {
      color: logoPath('Redmi_Color.svg'),
      black: logoPath('Redmi_Black.svg'),
      white: logoPath('Redmi_White.svg'),
    },
  },
  {
    id: 'oppo',
    name: 'OPPO',
    aliases: ['oppo', 'find x', 'reno'],
    brandColor: '#008037',
    assets: {
      color: logoPath('OPPO_Color.svg'),
      black: logoPath('OPPO_Black.svg'),
      white: logoPath('OPPO_White.svg'),
    },
  },
  {
    id: 'vivo',
    name: 'vivo',
    aliases: ['vivo'],
    brandColor: '#415fff',
    assets: {
      color: logoPath('VIvo_Color.svg'),
      black: logoPath('VIvo_Black.svg'),
      white: logoPath('VIvo_White.svg'),
    },
  },
  {
    id: 'iqoo',
    name: 'iQOO',
    aliases: ['iqoo'],
    brandColor: '#f6c643',
    assets: { color: logoPath('IQOO_Color.svg'), black: logoPath('IQOO.svg'), white: logoPath('IQOO_White.svg') },
  },
  {
    id: 'oneplus',
    name: 'OnePlus',
    aliases: ['oneplus', 'one plus'],
    brandColor: '#f5010c',
    assets: {
      color: logoPath('Oneplus_Color.svg'),
      black: logoPath('Oneplus_Black.svg'),
      white: logoPath('Oneplus_White.svg'),
    },
  },
  {
    id: 'honor',
    name: 'Honor',
    aliases: ['honor'],
    assets: { black: logoPath('honor.svg'), white: logoPath('HONOR_White.svg') },
  },
  {
    id: 'meizu',
    name: 'Meizu',
    aliases: ['meizu'],
    brandColor: '#00a7ea',
    assets: {
      color: logoPath('Meizu_Color.svg'),
      black: logoPath('Meizu-Black.svg'),
      white: logoPath('Meizu-White.svg'),
    },
  },
  {
    id: 'realme',
    name: 'realme',
    aliases: ['realme'],
    assets: { black: logoPath('Realme_Black.svg'), white: logoPath('Realme_White.svg') },
  },
  {
    id: '7artisans',
    name: '七工匠',
    aliases: ['7artisans', '七工匠'],
    brandColor: '#e02b20',
    assets: {
      color: logoPath('七工匠_Color.svg'),
      black: logoPath('七工匠_Black.svg'),
      white: logoPath('七工匠_White.svg'),
    },
  },
  {
    id: 'viltrox',
    name: '唯卓仕',
    aliases: ['viltrox', '唯卓仕'],
    assets: { black: logoPath('唯卓仕_Black.svg'), white: logoPath('唯卓仕_White.svg') },
  },
  {
    id: 'sirui',
    name: '思锐',
    aliases: ['sirui', '思锐'],
    brandColor: '#dd1f26',
    assets: {
      color: logoPath('思锐_Color.svg'),
      black: logoPath('思锐_Black.svg'),
      white: logoPath('思锐_White.svg'),
    },
  },
  {
    id: 'brightin-star',
    name: '星曜',
    aliases: ['brightin star', '星曜'],
    assets: { black: logoPath('星曜_Black.svg'), white: logoPath('星曜_White.svg') },
  },
  {
    id: 'yongnuo',
    name: '永诺',
    aliases: ['yongnuo', '永诺'],
    brandColor: '#e60012',
    assets: {
      color: logoPath('永诺_Color.svg'),
      black: logoPath('永诺_Black.svg'),
      white: logoPath('永诺_White.svg'),
    },
  },
  {
    id: 'laowa',
    name: '老蛙',
    aliases: ['laowa', '老蛙'],
    brandColor: '#d71920',
    assets: {
      color: logoPath('老蛙_Color.svg'),
      black: logoPath('老蛙_Black.svg'),
      white: logoPath('老蛙_White.svg'),
    },
  },
]
